<?php
$str = <<<EOF
    <Calendars>
        <Calendar>
            <UID>1</UID>
            <Name>SG Weekdays</Name>
            <IsBaseCalendar>1</IsBaseCalendar>
            <BaseCalendarUID>-1</BaseCalendarUID>
            <WeekDays>
            <WeekDay>
            <DayType>1</DayType>
            <DayWorking>0</DayWorking>
            </WeekDay>
            <WeekDay>
            <DayType>2</DayType>
            <DayWorking>1</DayWorking>
            <WorkingTimes>
                <WorkingTime>
                    <FromTime>08:00:00</FromTime>
                    <ToTime>12:00:00</ToTime>
                </WorkingTime>
                <WorkingTime>
                    <FromTime>13:00:00</FromTime>
                    <ToTime>17:00:00</ToTime>
                </WorkingTime>
            </WorkingTimes>
            </WeekDay>
            <WeekDay>
            <DayType>3</DayType>
            <DayWorking>1</DayWorking>
            <WorkingTimes>
                <WorkingTime>
                    <FromTime>08:00:00</FromTime>
                    <ToTime>12:00:00</ToTime>
                </WorkingTime>
                <WorkingTime>
                    <FromTime>13:00:00</FromTime>
                    <ToTime>17:00:00</ToTime>
                </WorkingTime>
            </WorkingTimes>
            </WeekDay>
            <WeekDay>
            <DayType>4</DayType>
            <DayWorking>1</DayWorking>
            <WorkingTimes>
                <WorkingTime>
                    <FromTime>08:00:00</FromTime>
                    <ToTime>12:00:00</ToTime>
                </WorkingTime>
                <WorkingTime>
                    <FromTime>13:00:00</FromTime>
                    <ToTime>17:00:00</ToTime>
                </WorkingTime>
            </WorkingTimes>
            </WeekDay>
            <WeekDay>
            <DayType>5</DayType>
            <DayWorking>1</DayWorking>
            <WorkingTimes>
                <WorkingTime>
                    <FromTime>08:00:00</FromTime>
                    <ToTime>12:00:00</ToTime>
                </WorkingTime>
                <WorkingTime>
                    <FromTime>13:00:00</FromTime>
                    <ToTime>17:00:00</ToTime>
                </WorkingTime>
            </WorkingTimes>
            </WeekDay>
            <WeekDay>
            <DayType>6</DayType>
            <DayWorking>1</DayWorking>
            <WorkingTimes>
                <WorkingTime>
                    <FromTime>08:00:00</FromTime>
                    <ToTime>12:00:00</ToTime>
                </WorkingTime>
                <WorkingTime>
                    <FromTime>13:00:00</FromTime>
                    <ToTime>17:00:00</ToTime>
                </WorkingTime>
            </WorkingTimes>
            </WeekDay>
            <WeekDay>
            <DayType>7</DayType>
            <DayWorking>0</DayWorking>
            </WeekDay>
            </WeekDays>
        </Calendar>
    </Calendars>
EOF;

return $str;